services:
  - type: web
    name: smartcampus
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd smartcampus && gunicorn smartcampus.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: smartcampus-db
          property: connectionString
      - key: DEBUG
        value: "False"

databases:
  - name: smartcampus-db
    databaseName: smartcampus
    user: smartcampus_user
