# Generated by Django 6.0.2 on 2026-03-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navigator.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.IntegerField(default=6)),
                ('periods_per_day', models.IntegerField(default=8)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navigator.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigator.timetablesettings')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('period_number', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Class', 'In Class')], default='Available', max_length=20)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigator.faculty')),
            ],
        ),
    ]
