# Generated by Django 6.0.2 on 2026-03-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0003_facultyuser_timetablesettings_periodtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
